### ISSUE TITLE
3d in dxf files

### ISSUE THREAD

**Issue by AbelSpecs** [ieskudero/three-dxf-viewer#4]
it can show 3D dxf files?

**Comment by ieskudero** [comment]
To tell you the truth, I didn't test it. Everything it shows is in 3D, but all the DXF files I tried where always in 2D. Can you send me a test DXF file? I could maybe fix it if it doesn't do it correctly

**Comment by AbelSpecs** [comment]
yeah sure, I tried this on sharedCAD to know how it should look, Thank you
[3DForm.zip](https://github.com/ieskudero/three-dxf-viewer/files/11932443/3DForm.zip)

**Comment by ieskudero** [comment]
Dear @AbelSpecs, I have changed the code to be able to draw 3D dxf files as much as I can. However, there are several problems here that are out of my scope for the moment:
1.- 3D polylines should be drawn correctly when there is no bulge. If there is a bulge a method from dxf parser should be changed, or use a new one.
2.- Checking the DXF format there are several types that the dxf parser is not parsing, such as 3D face, 3D solid ... so I can't draw them.

Since the file is parsed as polylines, it is drawn, but I guess that there are some entities that are not parsed since they should be parsed as subdivison surfaces. You can check how it draws removing 
```
this.controls.enableRotate = false;
this.controls.mouseButtons = {
	LEFT: MOUSE.PAN,
	MIDDLE: MOUSE.DOLLY,
	RIGHT: MOUSE.PAN
};
```

in the boilerplate3d.js class on any example.

I don't think I can do anything more at the moment, so if this solve the issue, I could close it.

**Comment by ieskudero** [comment]
If you are refering to DXF files, this is a good place, i guess:
https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-79fc.htm

here you can read the properties of each entity. With this you could make your own parser, or contribute to an existing one

**Comment by AbelSpecs** [comment]
Thank you
