### ISSUE TITLE
Is your library available in native JS without NodeJS ?

### ISSUE THREAD

**Issue by Xavlight** [ieskudero/three-dxf-viewer#5]
Hi,

Your bookshop works perfectly, and the quality is really very good.
I develop in PHP/HTML/JS, but not in nodejs (no NodeJS server available, I opted for PHP).
I would have liked to use your solution in native javascript (on the front end, like chrome or web browser, without server NodeJS).
I've been struggling for several days to convert it, but I'm having a lot of trouble.
There are a lot of imports.

Can you help me?

Sorry for my poor English.
French.

Xavlight

**Comment by ieskudero** [comment]
This is strange, since the code should work on browser without any help. Most browsers, if not all, already support ES6 classes already, so there is no need to transpile anything. Did you use the bundled version from npmjs? it is already bundled and can be used as a standalone js file (or should be used at least). You can download the main.js from inside dist folder from here:
[code](https://www.npmjs.com/package/three-dxf-viewer?activeTab=code)
Or you could use a CDN. You can find some using google, like this one:
https://www.jsdelivr.com/package/npm/three-dxf-viewer

Let me know if these helps.
